version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: dummy-be
    container_name: backend
    restart: always
    environment:
      # Use the Postgres container's name as the host in the connection string
      DATABASE_URL: "postgresql://postgres:postgres@postgres-container:5432/postgres"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node index.js"

  frontend:
    image: fe-dummy
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres-data:
